services:
  nodejs:
    container_name: nodejs
    image: node:20
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && node execute.js"
    restart: "no"
    networks:
      - bridge
  nginx:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - bridge
networks:
  bridge:
    driver: bridge